name: starter_kit_flutter
description: starter kit created by ishaf.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2

  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.6
  flutter_img: ^0.1.0+1
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^6.0.1
  hive: ^2.2.3
  injectable: ^2.1.2
  intl: ^0.18.0
  meta: ^1.9.1
  scroll_to_animate_tab: ^0.0.2+3
  scrollable_positioned_list: ^0.3.8
  percent_indicator: ^4.2.3

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  lint: ^2.0.1
  injectable_generator: ^2.1.6
  very_good_analysis: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - .env
  fonts:
    - family: 'bold'
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: 'medium'
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: 'regular'
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: 'CustomIcons'
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
